### ISSUE TITLE
No DSM/point cloud tiles results with Pleiades data

### ISSUE THREAD

**Issue by Thomas-Brd** [MISS3D/s2p#148]
Hi,

  I am working on DSM generation from Pléiades data with s2p but I have some bad results that I do not understand.. Indeed, all the points clouds (and DSM) of each tile are not calculated. The following files are missing in the output files for "empty" tiles:
- Height_map.tif
- rectified_disp.tif
- rectified_mask.png
- rpc_err.tif

These files are missing in the "pair_2" folder of the affected tiles.

Is this problem related to the configuration of the starting parameters?

I have provided you as an attachment the initial configuration file (config.json) I used, the output configuration file (config_out.json) and the resulting DSM.

Thank you.

[config_and-results.zip](https://github.com/MISS3D/s2p/files/1806631/config_and-results.zip)

Thomas.

**Comment by gfacciol** [comment]
Dear Thomas, 
The configuration seems good.  
If the rectified_disp.tif files are missing only in the pair_2 directories,  
then we might have a problem with the fusion. 
To help you out, could you send us the content of one of the tile subdirectories with problems? 

Have you tried running the pipeline independently on?
* pair_1: Plei-001.tif  -- Plei-002.tif 
* pair_2: Plei-001.tif  -- Plei-003.tif 

Please send us also the logs of all the tiles with:
 > zip logs.zip ` find -name *.log`

Best, 
Gabriele

**Comment by Thomas-Brd** [comment]
Thank you for this quick answer. Here is a link to the tile subdirectories with problems:
https://drive.google.com/open?id=1ri1DuSIN_J8yDCaPSG1ymc5lBSjtWVEf

I did not try to run the pipeline independently yet but I will try to do it.

Here is the logs of the tiles: 
[zip_logs.zip](https://github.com/MISS3D/s2p/files/1807005/zip_logs.zip)

Best,
Thomas

**Comment by gfacciol** [comment]
Thanks Thomas,

I found the problem in the pair_2/stdout.log
The stereo matching fails, probably due to an out of memory.


RUN: mgm -r -41 -R 94 -s vfit -t census -O 8
/home/psteer/Desktop/s2p/testdata/input_triplet/whataroa/../../testoutput/output_triplet/whataroa/tiles/row_0033498_height_1000/col_0004622_width_1000/pair_2/rectified_ref.tif
/home/psteer/Desktop/s2p/testdata/input_triplet/whataroa/../../testoutput/output_triplet/whataroa/tiles/row_0033498_height_1000/col_0004622_width_1000/pair_2/rectified_sec.tif
/home/psteer/Desktop/s2p/testdata/input_triplet/whataroa/../../testoutput/output_triplet/whataroa/tiles/row_0033498_height_1000/col_0004622_width_1000/pair_2/rectified_disp.tif

01234567
01234567Killed



The reason why this doesn't happen on the pair_1 is that the disparity
range in that case is smaller.


You have two options to fix this issue.
1) Quick&Dirty: recuce the size of the tiles: 700x700 instead of 1000x1000,
should reduce in half your memory usage.


  "tile_size": 1000,


2) The memory usage of the MGM correlator was addressed in a recent pull
request.
         https://github.com/gfacciol/s2p/tree/bump_mgm_multi
    You could fetch it and recompile mgm. To configure the new version of
the correlator use:

"matching_algorithm": "mgm_multi",

Best,
Gabriele

**Comment by Thomas-Brd** [comment]
Ok thanks! I will try the "mgm_multi" option.

All the best,

Thomas
