### ISSUE TITLE
regression

### ISSUE THREAD

**Issue by mnhrdt** [MISS3D/s2p#29]
If I clone the repository afresh and run the test suite, I obtain the following error and no DSM is produced:

Traceback (most recent call last):
  File "./s2p.py", line 365, in launch_parallel_calls
    r.get(3600)  # wait at most one hour per call
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
ValueError: need more than 2 values to unpack

In fact the tiles are correctly computed, but it fails when trying to join them.  I do not understand the error message, I do not see anything being unpacked here...

**Comment by carlodef** [comment]
Thank you for reporting this issue. It should be solved now in commit [71698d](https://github.com/carlodef/s2p/commit/71698dd7f766e80512e5d078ca58cd697b759bdf).

The bug was introduced in commit [4dfc6c](https://github.com/carlodef/s2p/commit/4dfc6c42f37a37ce1e8cc9627b163daee735144d) when the interface of function compute_dsm was changed without taking care of modifying all its invocations.

Sorry for having merged the pull request without noting this.
